export const actionType = {
    START_REFRESH_LOADING_STUDENT: 'START_REFRESH_LOADING_STUDENT',
    REFRESH_STUDENT_LIST_SUCCESS: 'REFRESH_STUDENT_LIST_SUCCESS',
    REFRESH_STUDENT_LIST_FAILED: 'REFRESH_STUDENT_LIST_FAILED',
    'MOVE_EXACTLY_TO_PAGE': 'MOVE_EXACTLY_TO_PAGE',
    'CHANGE_SEARCHING_VALUE': 'CHANGE_SEARCHING_VALUE',
    'MODIFY_STUDENT': {
        'SAVE': 'EDIT_STUDENT'
    },
    'ADD_STUDENT': {
        'SAVE': 'SAVE_NEW_STUDENT'
    }
}
